// Code generated by scripts/gen_public_facade; DO NOT EDIT.

package harness

import (
	context "context"
	tls "crypto/tls"
	core "github.com/xxnuo/deepseek-harness-go/internal/harness"
	io "io"
	net "net"
	http "net/http"
	time "time"
)

const ACPProtocolVersion = core.ACPProtocolVersion

const AuthorizationAlreadyRunning = core.AuthorizationAlreadyRunning

const AuthorizationAuthorized = core.AuthorizationAuthorized

const AuthorizationCancelled = core.AuthorizationCancelled

const AuthorizationClosed = core.AuthorizationClosed

const AuthorizationDeclined = core.AuthorizationDeclined

const AuthorizationDuplicateFlow = core.AuthorizationDuplicateFlow

const AuthorizationInvalidFlow = core.AuthorizationInvalidFlow

const AuthorizationNoFlow = core.AuthorizationNoFlow

const AuthorizationNotCommitted = core.AuthorizationNotCommitted

const AuthorizationPromptSecret = core.AuthorizationPromptSecret

const AuthorizationPromptSelect = core.AuthorizationPromptSelect

const AuthorizationPromptText = core.AuthorizationPromptText

const AuthorizationSettledAuthorized = core.AuthorizationSettledAuthorized

const AuthorizationSettledCancelled = core.AuthorizationSettledCancelled

const AuthorizationSettledFailed = core.AuthorizationSettledFailed

const AuthorizationUnknownMethod = core.AuthorizationUnknownMethod

const ClaudeCodePermissionAcceptEdits = core.ClaudeCodePermissionAcceptEdits

const ClaudeCodePermissionAuto = core.ClaudeCodePermissionAuto

const ClaudeCodePermissionBypassPermissions = core.ClaudeCodePermissionBypassPermissions

const ClaudeCodePermissionDontAsk = core.ClaudeCodePermissionDontAsk

const ClaudeCodePermissionPlan = core.ClaudeCodePermissionPlan

const CodexPermissionApproveForMe = core.CodexPermissionApproveForMe

const CodexPermissionDangerouslyBypassApprovalsAndSandbox = core.CodexPermissionDangerouslyBypassApprovalsAndSandbox

const CodexPermissionNever = core.CodexPermissionNever

const CredentialRecordAPIKey = core.CredentialRecordAPIKey

const CredentialRecordGrant = core.CredentialRecordGrant

const CredentialRecordUpdated = core.CredentialRecordUpdated

const CredentialReferenceUpdated = core.CredentialReferenceUpdated

const DeepSeekFileExpirySeconds = core.DeepSeekFileExpirySeconds

const DeepSeekFileRefreshSeconds = core.DeepSeekFileRefreshSeconds

const DeepSeekMaxChatImageBytes = core.DeepSeekMaxChatImageBytes

const DeepSeekMaxFileExpirySeconds = core.DeepSeekMaxFileExpirySeconds

const DeepSeekMaxFileUploadBytes = core.DeepSeekMaxFileUploadBytes

const DeepSeekMaxRequestImages = core.DeepSeekMaxRequestImages

const DeepSeekMaxStoredFileBytes = core.DeepSeekMaxStoredFileBytes

const DeepSeekMaxStoredFileCount = core.DeepSeekMaxStoredFileCount

const DeepSeekMinFileExpirySeconds = core.DeepSeekMinFileExpirySeconds

const DeepSeekQuotaCleanupBatch = core.DeepSeekQuotaCleanupBatch

const DeepSeekRequestImageBytes = core.DeepSeekRequestImageBytes

const DeepSeekRequestImagePixels = core.DeepSeekRequestImagePixels

const DefaultFileReferenceMaxEntries = core.DefaultFileReferenceMaxEntries

const DefaultFileReferenceMaxResults = core.DefaultFileReferenceMaxResults

const DefaultHookStderrSummaryMaxChars = core.DefaultHookStderrSummaryMaxChars

const DefaultHookTimeout = core.DefaultHookTimeout

const DefaultMaxRequestImageBytes = core.DefaultMaxRequestImageBytes

const DefaultSQLiteBusyTimeout = core.DefaultSQLiteBusyTimeout

const DefaultSQLitePreparedSessionCacheSize = core.DefaultSQLitePreparedSessionCacheSize

const DefaultSQLiteWriteBatchMaxDelay = core.DefaultSQLiteWriteBatchMaxDelay

const DefaultSessionReferenceBytes = core.DefaultSessionReferenceBytes

const DefaultSessionReferenceCandidates = core.DefaultSessionReferenceCandidates

const DomainAlreadyOpen = core.DomainAlreadyOpen

const DomainClosed = core.DomainClosed

const DomainFacetUnsupported = core.DomainFacetUnsupported

const DomainInvalidRecord = core.DomainInvalidRecord

const DomainMissingKey = core.DomainMissingKey

const E2BDir = core.E2BDir

const E2BFile = core.E2BFile

const E2BSymlink = core.E2BSymlink

const FileReferencePrompt = core.FileReferencePrompt

const HookDialectClaudeCode = core.HookDialectClaudeCode

const HookDialectCodex = core.HookDialectCodex

const IndexInjectionBody = core.IndexInjectionBody

const IndexInjectionGlobal = core.IndexInjectionGlobal

const IndexInjectionHTML = core.IndexInjectionHTML

const IndexInjectionHead = core.IndexInjectionHead

const IndexInjectionScript = core.IndexInjectionScript

const IndexInjectionScriptSrc = core.IndexInjectionScriptSrc

const IndexInjectionStyle = core.IndexInjectionStyle

const InvariantErrorCode = core.InvariantErrorCode

const LSPFindReferences = core.LSPFindReferences

const LSPGoToDefinition = core.LSPGoToDefinition

const LSPGoToImplementation = core.LSPGoToImplementation

const LSPHover = core.LSPHover

const MCPTransportStdio = core.MCPTransportStdio

const MCPTransportStreamableHTTP = core.MCPTransportStreamableHTTP

const MaxSQLiteBusyTimeout = core.MaxSQLiteBusyTimeout

const MaxSQLiteWriteBatchDelay = core.MaxSQLiteWriteBatchDelay

const MaxSessionReferences = core.MaxSessionReferences

const OffloadedImageText = core.OffloadedImageText

const PythonProtocolFD = core.PythonProtocolFD

const RetryAlways = core.RetryAlways

const RetryNormal = core.RetryNormal

const SQLiteJournalDelete = core.SQLiteJournalDelete

const SQLiteJournalPersist = core.SQLiteJournalPersist

const SQLiteJournalTruncate = core.SQLiteJournalTruncate

const SQLiteJournalWAL = core.SQLiteJournalWAL

const SessionFormatVersion = core.SessionFormatVersion

const SessionReferenceBudgetExceeded = core.SessionReferenceBudgetExceeded

const SessionReferenceCancelled = core.SessionReferenceCancelled

const SessionReferenceInvalidConfig = core.SessionReferenceInvalidConfig

const SessionReferenceInvalidReference = core.SessionReferenceInvalidReference

const SessionReferenceReadFailed = core.SessionReferenceReadFailed

const SessionReferenceScheme = core.SessionReferenceScheme

const SessionReferenceSelfReference = core.SessionReferenceSelfReference

const SessionReferenceTooMany = core.SessionReferenceTooMany

const SessionSQLiteApplicationID = core.SessionSQLiteApplicationID

const SessionSQLiteSchemaVersion = core.SessionSQLiteSchemaVersion

const SessionTelemetryChannelLedger = core.SessionTelemetryChannelLedger

const SessionTelemetryChannelOps = core.SessionTelemetryChannelOps

const SessionTelemetryModeDisabled = core.SessionTelemetryModeDisabled

const SessionTelemetryModeFeedbackOnly = core.SessionTelemetryModeFeedbackOnly

const SessionTelemetryModeFull = core.SessionTelemetryModeFull

const SessionTelemetrySeverityError = core.SessionTelemetrySeverityError

const SessionTelemetrySeverityInfo = core.SessionTelemetrySeverityInfo

const SessionTelemetrySeverityWarn = core.SessionTelemetrySeverityWarn

const SessionTelemetrySharingDisabled = core.SessionTelemetrySharingDisabled

const SessionTelemetrySharingFeedbackOnly = core.SessionTelemetrySharingFeedbackOnly

const SessionTelemetrySharingFull = core.SessionTelemetrySharingFull

const SessionTitleAllPrompts = core.SessionTitleAllPrompts

const SessionTitleFirstPrompt = core.SessionTitleFirstPrompt

const StorageBackendNotFound = core.StorageBackendNotFound

const StorageClosed = core.StorageClosed

const StorageDuplicateBackend = core.StorageDuplicateBackend

const StorageDuplicateMount = core.StorageDuplicateMount

const StorageFormNotMounted = core.StorageFormNotMounted

const StorageMalformedMedium = core.StorageMalformedMedium

const StorageSQLiteSchemaVersion = core.StorageSQLiteSchemaVersion

const StorageVersionMismatch = core.StorageVersionMismatch

const SubagentAborted = core.SubagentAborted

const SubagentCompleted = core.SubagentCompleted

const SubagentDescriptorVersion = core.SubagentDescriptorVersion

const SubagentError = core.SubagentError

const SubagentMaxTokens = core.SubagentMaxTokens

const SubagentRefusal = core.SubagentRefusal

const SubagentReportNextStep = core.SubagentReportNextStep

const SubagentReportQuiet = core.SubagentReportQuiet

const TerminalShellDialectBash = core.TerminalShellDialectBash

const TerminalShellDialectPwsh = core.TerminalShellDialectPwsh

const TerminalSignalHangup = core.TerminalSignalHangup

const TerminalSignalInterrupt = core.TerminalSignalInterrupt

const TerminalSignalKill = core.TerminalSignalKill

const TerminalSignalStop = core.TerminalSignalStop

const TerminalSignalTerminate = core.TerminalSignalTerminate

const TerminalWaitInferredIdle = core.TerminalWaitInferredIdle

const TerminalWaitSessionExit = core.TerminalWaitSessionExit

const TerminalWaitStdinRead = core.TerminalWaitStdinRead

const TerminalWaitTimeout = core.TerminalWaitTimeout

var DefaultFileReferenceExcludedDirectories = core.DefaultFileReferenceExcludedDirectories

var ErrEngineClosed = core.ErrEngineClosed

var PythonWireFrameFields = core.PythonWireFrameFields

type ACPSubagentConfig = core.ACPSubagentConfig

type ACPSubagentProvider = core.ACPSubagentProvider

type ActiveFileReferenceToken = core.ActiveFileReferenceToken

type AgentPresetConflictError = core.AgentPresetConflictError

type AgentRequestInvariant = core.AgentRequestInvariant

type AgentTeamConfig = core.AgentTeamConfig

type AnthropicProvider = core.AnthropicProvider

type AuthorizationDeclinedError = core.AuthorizationDeclinedError

type AuthorizationEntry = core.AuthorizationEntry

type AuthorizationError = core.AuthorizationError

type AuthorizationFlow = core.AuthorizationFlow

type AuthorizationInteraction = core.AuthorizationInteraction

type AuthorizationMethod = core.AuthorizationMethod

type AuthorizationNotice = core.AuthorizationNotice

type AuthorizationOutcome = core.AuthorizationOutcome

type AuthorizationPrompt = core.AuthorizationPrompt

type AuthorizationPromptKind = core.AuthorizationPromptKind

type AuthorizationPromptOption = core.AuthorizationPromptOption

type AuthorizationRequest = core.AuthorizationRequest

type AuthorizationService = core.AuthorizationService

type AuthorizationSession = core.AuthorizationSession

type AuthorizationSettlement = core.AuthorizationSettlement

type AuthorizationSettlementListener = core.AuthorizationSettlementListener

type AuthorizationStatus = core.AuthorizationStatus

type BackendRegistry = core.BackendRegistry

type BootEntry = core.BootEntry

type BootGraph = core.BootGraph

type ChatContentPart = core.ChatContentPart

type ChatImage = core.ChatImage

type ChatMessage = core.ChatMessage

type ChatRequest = core.ChatRequest

type ClaudeCodePermissionMode = core.ClaudeCodePermissionMode

type ClaudeCodeSubagentConfig = core.ClaudeCodeSubagentConfig

type ClaudeCodeSubagentProvider = core.ClaudeCodeSubagentProvider

type ClientTimeZoneError = core.ClientTimeZoneError

type CodexPermissionMode = core.CodexPermissionMode

type CodexSubagentConfig = core.CodexSubagentConfig

type CodexSubagentProvider = core.CodexSubagentProvider

type CommandResult = core.CommandResult

type CompactionConfig = core.CompactionConfig

type Completion = core.Completion

type Config = core.Config

type ContentBlock = core.ContentBlock

type CordisInspectMethodManifest = core.CordisInspectMethodManifest

type CordisInspectProviderManifest = core.CordisInspectProviderManifest

type CordisInspectProviderView = core.CordisInspectProviderView

type CordisInspectQueryResolution = core.CordisInspectQueryResolution

type CordisInspectResolveAck = core.CordisInspectResolveAck

type CreateTeamTaskRequest = core.CreateTeamTaskRequest

type CredentialEvent = core.CredentialEvent

type CredentialEventKind = core.CredentialEventKind

type CredentialInfo = core.CredentialInfo

type CredentialKey = core.CredentialKey

type CredentialRecord = core.CredentialRecord

type CredentialRecordEntry = core.CredentialRecordEntry

type CredentialRecordInfo = core.CredentialRecordInfo

type CredentialRecordKind = core.CredentialRecordKind

type CredentialRef = core.CredentialRef

type CredentialService = core.CredentialService

type DSHSDKSubagentConfig = core.DSHSDKSubagentConfig

type DSHSDKSubagentProvider = core.DSHSDKSubagentProvider

type DeepSeekFileConnection = core.DeepSeekFileConnection

type DeepSeekFileObject = core.DeepSeekFileObject

type DeepSeekFilePage = core.DeepSeekFilePage

type DeepSeekFilePolicy = core.DeepSeekFilePolicy

type DeepSeekFileReference = core.DeepSeekFileReference

type DeepSeekFileStore = core.DeepSeekFileStore

type DeepSeekFilesClient = core.DeepSeekFilesClient

type DeepSeekFilesError = core.DeepSeekFilesError

type DeepSeekUploadIndex = core.DeepSeekUploadIndex

type DeepSeekUploadRecord = core.DeepSeekUploadRecord

type Delta = core.Delta

type Domain = core.Domain

type DomainChange = core.DomainChange

type DomainError = core.DomainError

type DomainErrorCode = core.DomainErrorCode

type DomainFacility = core.DomainFacility

type DomainGlobal = core.DomainGlobal

type DomainGlobalSpec = core.DomainGlobalSpec

type DomainSpec = core.DomainSpec

type DomainTable = core.DomainTable

type DomainTableSpec = core.DomainTableSpec

type DomainValueParser = core.DomainValueParser

type DynamicCordisActiveRun = core.DynamicCordisActiveRun

type DynamicCordisClientSource = core.DynamicCordisClientSource

type DynamicCordisCode = core.DynamicCordisCode

type DynamicCordisDefineReceipt = core.DynamicCordisDefineReceipt

type DynamicCordisDefineRequest = core.DynamicCordisDefineRequest

type DynamicCordisErrorDetails = core.DynamicCordisErrorDetails

type DynamicCordisHostHalfResult = core.DynamicCordisHostHalfResult

type DynamicCordisInventoryPackage = core.DynamicCordisInventoryPackage

type DynamicCordisInventoryRow = core.DynamicCordisInventoryRow

type DynamicCordisInvokeResult = core.DynamicCordisInvokeResult

type DynamicCordisPluginSelector = core.DynamicCordisPluginSelector

type DynamicCordisRenderFailure = core.DynamicCordisRenderFailure

type DynamicCordisRunResolution = core.DynamicCordisRunResolution

type DynamicCordisRunResponse = core.DynamicCordisRunResponse

type DynamicCordisStopResponse = core.DynamicCordisStopResponse

type DynamicCordisUndefineReceipt = core.DynamicCordisUndefineReceipt

type E2BCommandError = core.E2BCommandError

type E2BCommandHandle = core.E2BCommandHandle

type E2BCommandOptions = core.E2BCommandOptions

type E2BCommandResult = core.E2BCommandResult

type E2BCommands = core.E2BCommands

type E2BConfig = core.E2BConfig

type E2BEntryInfo = core.E2BEntryInfo

type E2BFSInfo = core.E2BFSInfo

type E2BFSWriteIntent = core.E2BFSWriteIntent

type E2BFSWriteOutcome = core.E2BFSWriteOutcome

type E2BFileSystem = core.E2BFileSystem

type E2BFileType = core.E2BFileType

type E2BFiles = core.E2BFiles

type E2BPTY = core.E2BPTY

type E2BPTYOptions = core.E2BPTYOptions

type E2BProcess = core.E2BProcess

type E2BRuntime = core.E2BRuntime

type E2BSandbox = core.E2BSandbox

type E2BSandboxFactory = core.E2BSandboxFactory

type E2BSubprocessRuntime = core.E2BSubprocessRuntime

type E2BSubprocessSpec = core.E2BSubprocessSpec

type E2BTerminal = core.E2BTerminal

type EchoProvider = core.EchoProvider

type EncodedImageAttachment = core.EncodedImageAttachment

type Engine = core.Engine

type Event = core.Event

type ExaSearchProvider = core.ExaSearchProvider

type ExaSearchProviderOptions = core.ExaSearchProviderOptions

type FileReferenceCandidate = core.FileReferenceCandidate

type FileReferenceConfig = core.FileReferenceConfig

type GoalBlockReason = core.GoalBlockReason

type GoalView = core.GoalView

type HTTPWebFetchConfig = core.HTTPWebFetchConfig

type HTTPWebFetchProvider = core.HTTPWebFetchProvider

type HistoryEntry = core.HistoryEntry

type HookBridge = core.HookBridge

type HookBridgeConfig = core.HookBridgeConfig

type HookCommand = core.HookCommand

type HookDialect = core.HookDialect

type HookOutput = core.HookOutput

type HookPointRequest = core.HookPointRequest

type HookPointResult = core.HookPointResult

type HookRunResult = core.HookRunResult

type ImageAttachmentRef = core.ImageAttachmentRef

type ImageDimensions = core.ImageDimensions

type ImageReadValue = core.ImageReadValue

type ImageRequestPolicy = core.ImageRequestPolicy

type IndexInjection = core.IndexInjection

type IndexInjectionKind = core.IndexInjectionKind

type IndexInjectionPlacement = core.IndexInjectionPlacement

type IndexInjectionProvider = core.IndexInjectionProvider

type IndexTransform = core.IndexTransform

type InvalidDomainRecord = core.InvalidDomainRecord

type InvariantDisposer = core.InvariantDisposer

type InvariantError = core.InvariantError

type InvariantFailure = core.InvariantFailure

type InvariantInstaller = core.InvariantInstaller

type InvariantRegistry = core.InvariantRegistry

type InvariantScope = core.InvariantScope

type JSONLSessionStore = core.JSONLSessionStore

type JSONStorageBackend = core.JSONStorageBackend

type JSONStorageConfig = core.JSONStorageConfig

type KVFacet = core.KVFacet

type KVSnapshot = core.KVSnapshot

type KVUnit = core.KVUnit

type KVUnitDescriptor = core.KVUnitDescriptor

type LSPError = core.LSPError

type LSPHoverResult = core.LSPHoverResult

type LSPLocation = core.LSPLocation

type LSPPosition = core.LSPPosition

type LSPProvider = core.LSPProvider

type LSPProviderQuery = core.LSPProviderQuery

type LSPQuery = core.LSPQuery

type LSPQueryResult = core.LSPQueryResult

type LSPRange = core.LSPRange

type LSPStdioConfig = core.LSPStdioConfig

type LSPToolConfig = core.LSPToolConfig

type LaunchEnvironmentSnapshot = core.LaunchEnvironmentSnapshot

type LlmFailure = core.LlmFailure

type LlmRequestError = core.LlmRequestError

type LocalSandboxFactory = core.LocalSandboxFactory

type MCPConfig = core.MCPConfig

type MCPConnection = core.MCPConnection

type MCPReconnectConfig = core.MCPReconnectConfig

type MergedHookOutcome = core.MergedHookOutcome

type ModelInfo = core.ModelInfo

type ModelSelection = core.ModelSelection

type OpenAIProvider = core.OpenAIProvider

type OpenAIResponsesProvider = core.OpenAIResponsesProvider

type Option = core.Option

type ParsedSessionReferenceText = core.ParsedSessionReferenceText

type PerplexitySearchProvider = core.PerplexitySearchProvider

type PerplexitySearchProviderOptions = core.PerplexitySearchProviderOptions

type PreparedSessionReferenceMessage = core.PreparedSessionReferenceMessage

type ProjectionChange = core.ProjectionChange

type ProjectionChangeListener = core.ProjectionChangeListener

type ProjectionDefinition = core.ProjectionDefinition

type ProjectionResult = core.ProjectionResult

type ProjectionSnapshot = core.ProjectionSnapshot

type PromptContentPart = core.PromptContentPart

type PromptRequest = core.PromptRequest

type PromptResult = core.PromptResult

type Provider = core.Provider

type ProviderError = core.ProviderError

type ProviderRetryPolicy = core.ProviderRetryPolicy

type PythonBootMessage = core.PythonBootMessage

type PythonChildFrame = core.PythonChildFrame

type PythonDoneError = core.PythonDoneError

type PythonDoneValueCheck = core.PythonDoneValueCheck

type PythonErrorClass = core.PythonErrorClass

type PythonJSONMember = core.PythonJSONMember

type PythonJSONObject = core.PythonJSONObject

type PythonNamespace = core.PythonNamespace

type PythonReplyError = core.PythonReplyError

type PythonReplyOK = core.PythonReplyOK

type PythonRunMessage = core.PythonRunMessage

type PythonUTF16String = core.PythonUTF16String

type PythonWireFieldSet = core.PythonWireFieldSet

type RPCError = core.RPCError

type RepeatToolReminderConfig = core.RepeatToolReminderConfig

type RequestImageAttachment = core.RequestImageAttachment

type ResolvedCredential = core.ResolvedCredential

type RetryPolicy = core.RetryPolicy

type RetryPolicyProvider = core.RetryPolicyProvider

type RuntimeInvariantConfig = core.RuntimeInvariantConfig

type SQLiteJournalMode = core.SQLiteJournalMode

type SQLiteSessionStore = core.SQLiteSessionStore

type SQLiteSessionStoreOptions = core.SQLiteSessionStoreOptions

type SQLiteStorageBackend = core.SQLiteStorageBackend

type SQLiteStorageConfig = core.SQLiteStorageConfig

type SendTeamMessageRequest = core.SendTeamMessageRequest

type SendTeamMessageResult = core.SendTeamMessageResult

type Server = core.Server

type Session = core.Session

type SessionConflictError = core.SessionConflictError

type SessionHeader = core.SessionHeader

type SessionInspection = core.SessionInspection

type SessionInvariant = core.SessionInvariant

type SessionLocation = core.SessionLocation

type SessionPersistenceRevision = core.SessionPersistenceRevision

type SessionPersistenceSnapshot = core.SessionPersistenceSnapshot

type SessionProjectionCacheConfig = core.SessionProjectionCacheConfig

type SessionProjectionRegistry = core.SessionProjectionRegistry

type SessionRawArtifact = core.SessionRawArtifact

type SessionReferenceCandidate = core.SessionReferenceCandidate

type SessionReferenceConfig = core.SessionReferenceConfig

type SessionReferenceContext = core.SessionReferenceContext

type SessionReferenceError = core.SessionReferenceError

type SessionReferenceErrorCode = core.SessionReferenceErrorCode

type SessionReferenceInput = core.SessionReferenceInput

type SessionReferenceMentionCandidate = core.SessionReferenceMentionCandidate

type SessionStore = core.SessionStore

type SessionSummary = core.SessionSummary

type SessionTelemetryChannel = core.SessionTelemetryChannel

type SessionTelemetryConfig = core.SessionTelemetryConfig

type SessionTelemetryMode = core.SessionTelemetryMode

type SessionTelemetryOTLPExporterConfig = core.SessionTelemetryOTLPExporterConfig

type SessionTelemetryProcessorConfig = core.SessionTelemetryProcessorConfig

type SessionTelemetryRecord = core.SessionTelemetryRecord

type SessionTelemetrySeverity = core.SessionTelemetrySeverity

type SessionTelemetrySharingStatus = core.SessionTelemetrySharingStatus

type SessionTelemetrySink = core.SessionTelemetrySink

type SessionTitleAutomaticMode = core.SessionTitleAutomaticMode

type SessionTitleConfig = core.SessionTitleConfig

type SessionTitleLLMConfig = core.SessionTitleLLMConfig

type SessionTitleModelProvenance = core.SessionTitleModelProvenance

type SessionTitleProvider = core.SessionTitleProvider

type SessionTitleProviderRequest = core.SessionTitleProviderRequest

type SessionTitleProviderResult = core.SessionTitleProviderResult

type SessionTitleSnapshot = core.SessionTitleSnapshot

type SessionTitleSource = core.SessionTitleSource

type SessionTitleUserMessage = core.SessionTitleUserMessage

type SkillDefinition = core.SkillDefinition

type SpawnTeammateRequest = core.SpawnTeammateRequest

type SpawnTeammateResult = core.SpawnTeammateResult

type SpillConfig = core.SpillConfig

type StorageBackend = core.StorageBackend

type StorageDomainConfig = core.StorageDomainConfig

type StorageError = core.StorageError

type StorageErrorCode = core.StorageErrorCode

type StorageHub = core.StorageHub

type StorageRuntimeConfig = core.StorageRuntimeConfig

type SubagentAgentOptions = core.SubagentAgentOptions

type SubagentCapabilities = core.SubagentCapabilities

type SubagentProvider = core.SubagentProvider

type SubagentProviderInfo = core.SubagentProviderInfo

type SubagentResult = core.SubagentResult

type SubagentRun = core.SubagentRun

type SubagentStartRequest = core.SubagentStartRequest

type SubagentStopReason = core.SubagentStopReason

type SubagentToolConfig = core.SubagentToolConfig

type SubagentToolFilter = core.SubagentToolFilter

type TeamError = core.TeamError

type TeamFold = core.TeamFold

type TeamMemberSnapshot = core.TeamMemberSnapshot

type TeamMemberView = core.TeamMemberView

type TeamMessageSnapshot = core.TeamMessageSnapshot

type TeamService = core.TeamService

type TeamTaskSnapshot = core.TeamTaskSnapshot

type TeamTaskView = core.TeamTaskView

type TeamWaitResult = core.TeamWaitResult

type TerminalBackend = core.TerminalBackend

type TerminalBackendCleanupError = core.TerminalBackendCleanupError

type TerminalBackendSession = core.TerminalBackendSession

type TerminalBackendSpawnSpec = core.TerminalBackendSpawnSpec

type TerminalConfig = core.TerminalConfig

type TerminalError = core.TerminalError

type TerminalReadRequest = core.TerminalReadRequest

type TerminalReadResult = core.TerminalReadResult

type TerminalSendOperation = core.TerminalSendOperation

type TerminalSendRead = core.TerminalSendRead

type TerminalSendRequest = core.TerminalSendRequest

type TerminalSendResult = core.TerminalSendResult

type TerminalSessionSnapshot = core.TerminalSessionSnapshot

type TerminalSessionStatus = core.TerminalSessionStatus

type TerminalSignalResult = core.TerminalSignalResult

type TerminalSpawnRequest = core.TerminalSpawnRequest

type TerminalSpawnResult = core.TerminalSpawnResult

type TerminalToolConfig = core.TerminalToolConfig

type TimeContextConfig = core.TimeContextConfig

type TmuxContextConfig = core.TmuxContextConfig

type TodoItem = core.TodoItem

type Tool = core.Tool

type ToolCall = core.ToolCall

type ToolCallDelta = core.ToolCallDelta

type ToolConstrainedSampling = core.ToolConstrainedSampling

type ToolError = core.ToolError

type ToolExecutor = core.ToolExecutor

type ToolResult = core.ToolResult

type ToolResultPruneConfig = core.ToolResultPruneConfig

type ToolSchema = core.ToolSchema

type UpdateTeamTaskRequest = core.UpdateTeamTaskRequest

type WebError = core.WebError

type WebFetchBody = core.WebFetchBody

type WebFetchProvider = core.WebFetchProvider

type WebFetchRequest = core.WebFetchRequest

type WebFetchResult = core.WebFetchResult

type WebSearchProvider = core.WebSearchProvider

type WebSearchRequest = core.WebSearchRequest

type WebSearchResult = core.WebSearchResult

type WebSearchSource = core.WebSearchSource

type WebToolConfig = core.WebToolConfig

type Workspace = core.Workspace

type WorkspaceFileSearch = core.WorkspaceFileSearch

func ACPSubagentStopReason(reason string) SubagentStopReason {
	return core.ACPSubagentStopReason(reason)
}

func CheckPythonDoneValue(value any, maxBytes int) (PythonDoneValueCheck, error) {
	return core.CheckPythonDoneValue(value, maxBytes)
}

func DecodeSessionReferenceURI(uri string) (string, error) {
	return core.DecodeSessionReferenceURI(uri)
}

func DefaultAgentTeamConfig() AgentTeamConfig {
	return core.DefaultAgentTeamConfig()
}

func DefaultConfig() Config {
	return core.DefaultConfig()
}

func DefaultHTTPWebFetchConfig() HTTPWebFetchConfig {
	return core.DefaultHTTPWebFetchConfig()
}

func DefaultWebToolConfig() WebToolConfig {
	return core.DefaultWebToolConfig()
}

func DomainDescriptor(spec DomainSpec) KVUnitDescriptor {
	return core.DomainDescriptor(spec)
}

func EmbeddedAssetRevision() (string, error) {
	return core.EmbeddedAssetRevision()
}

func EncodePythonJSONPlain(value any) (string, error) {
	return core.EncodePythonJSONPlain(value)
}

func EncodeSessionPathSegment(raw string) string {
	return core.EncodeSessionPathSegment(raw)
}

func EncodeSessionReferenceURI(sessionID string) string {
	return core.EncodeSessionReferenceURI(sessionID)
}

func FallbackSessionTitle(input string, maxWords, maxBytes int) string {
	return core.FallbackSessionTitle(input, maxWords, maxBytes)
}

func FoldSessionTitle(events []Event) (SessionTitleSnapshot, bool) {
	return core.FoldSessionTitle(events)
}

func FoldTeam(rootID string, events []Event) (TeamFold, error) {
	return core.FoldTeam(rootID, events)
}

func FormatFileReferenceMention(candidate FileReferenceCandidate, preserveQuote bool) (string, bool) {
	return core.FormatFileReferenceMention(candidate, preserveQuote)
}

func FormatSessionReferenceMention(reference SessionReferenceInput) string {
	return core.FormatSessionReferenceMention(reference)
}

func HasNonLosslessJSONNumber(value any) bool {
	return core.HasNonLosslessJSONNumber(value)
}

func HasUnsafeJSONIntegerToken(line string) bool {
	return core.HasUnsafeJSONIntegerToken(line)
}

func HookMatcherDiagnostic(matcher *string, dialect HookDialect) string {
	return core.HookMatcherDiagnostic(matcher, dialect)
}

func IsAuthorizationError(err error, code string) bool {
	return core.IsAuthorizationError(err, code)
}

func IsCredentialKeySegment(value string) bool {
	return core.IsCredentialKeySegment(value)
}

func IsDomainError(err error, code DomainErrorCode) bool {
	return core.IsDomainError(err, code)
}

func IsSessionReferenceError(err error, code SessionReferenceErrorCode) bool {
	return core.IsSessionReferenceError(err, code)
}

func IsStorageError(err error, code StorageErrorCode) bool {
	return core.IsStorageError(err, code)
}

func JSONDomainParser[T any](validate func(T) error) DomainValueParser {
	return core.JSONDomainParser[T](validate)
}

func LANIPv4Addresses() []string {
	return core.LANIPv4Addresses()
}

func MCPPublicToolName(serverName, rawName string) string {
	return core.MCPPublicToolName(serverName, rawName)
}

func MatchesHookMatcher(matcher *string, query string, dialect HookDialect) bool {
	return core.MatchesHookMatcher(matcher, query, dialect)
}

func MaterializeEmbeddedAssets(dataDir string) (AssetPaths, error) {
	return core.MaterializeEmbeddedAssets(dataDir)
}

func MergeHookOutputs(outputs []HookOutput) MergedHookOutcome {
	return core.MergeHookOutputs(outputs)
}

func New(opts ...Option) (*Engine, error) {
	return core.New(opts...)
}

func NewACPSubagentProvider(config ACPSubagentConfig) (*ACPSubagentProvider, error) {
	return core.NewACPSubagentProvider(config)
}

func NewAnthropicProvider(id, baseURL, apiKey, model string) *AnthropicProvider {
	return core.NewAnthropicProvider(id, baseURL, apiKey, model)
}

func NewBackendRegistry() *BackendRegistry {
	return core.NewBackendRegistry()
}

func NewBashTerminalBackend(config TerminalConfig) (TerminalBackend, error) {
	return core.NewBashTerminalBackend(config)
}

func NewClaudeCodeSubagentProvider(config ClaudeCodeSubagentConfig) (*ClaudeCodeSubagentProvider, error) {
	return core.NewClaudeCodeSubagentProvider(config)
}

func NewCodexSubagentProvider(config CodexSubagentConfig) (*CodexSubagentProvider, error) {
	return core.NewCodexSubagentProvider(config)
}

func NewCredentialKey(scope, id string) (CredentialKey, error) {
	return core.NewCredentialKey(scope, id)
}

func NewDSHSDKSubagentProvider(config DSHSDKSubagentConfig) (*DSHSDKSubagentProvider, error) {
	return core.NewDSHSDKSubagentProvider(config)
}

func NewDeepSeekFileStore(index *DeepSeekUploadIndex, client *http.Client) *DeepSeekFileStore {
	return core.NewDeepSeekFileStore(index, client)
}

func NewDeepSeekFilesClient(baseURL, apiKey string, client *http.Client) *DeepSeekFilesClient {
	return core.NewDeepSeekFilesClient(baseURL, apiKey, client)
}

func NewDeepSeekUploadIndex(path string) *DeepSeekUploadIndex {
	return core.NewDeepSeekUploadIndex(path)
}

func NewDomainFacility(hub *StorageHub, backend string, routes map[string]string) (*DomainFacility, error) {
	return core.NewDomainFacility(hub, backend, routes)
}

func NewE2BCloudSandboxFactory() E2BSandboxFactory {
	return core.NewE2BCloudSandboxFactory()
}

func NewE2BFileSystem(runtime *E2BRuntime) *E2BFileSystem {
	return core.NewE2BFileSystem(runtime)
}

func NewE2BRuntime(ctx context.Context, config E2BConfig) (*E2BRuntime, error) {
	return core.NewE2BRuntime(ctx, config)
}

func NewE2BSubprocessRuntime(runtime *E2BRuntime) *E2BSubprocessRuntime {
	return core.NewE2BSubprocessRuntime(runtime)
}

func NewEchoProvider(id, name string) *EchoProvider {
	return core.NewEchoProvider(id, name)
}

func NewExaSearchProvider(options ExaSearchProviderOptions) *ExaSearchProvider {
	return core.NewExaSearchProvider(options)
}

func NewHTTPWebFetchProvider(configs ...HTTPWebFetchConfig) *HTTPWebFetchProvider {
	return core.NewHTTPWebFetchProvider(configs...)
}

func NewHookBridge(config HookBridgeConfig) (*HookBridge, error) {
	return core.NewHookBridge(config)
}

func NewInvariantRegistry(config RuntimeInvariantConfig) (*InvariantRegistry, error) {
	return core.NewInvariantRegistry(config)
}

func NewJSONLSessionStore(root string) (*JSONLSessionStore, error) {
	return core.NewJSONLSessionStore(root)
}

func NewJSONStorageBackend(root string) (*JSONStorageBackend, error) {
	return core.NewJSONStorageBackend(root)
}

func NewLlmRequestError(failure LlmFailure, cause error) *LlmRequestError {
	return core.NewLlmRequestError(failure, cause)
}

func NewLocalSandboxFactory(root string) E2BSandboxFactory {
	return core.NewLocalSandboxFactory(root)
}

func NewOpenAIProvider(id, baseURL, apiKey, model string) *OpenAIProvider {
	return core.NewOpenAIProvider(id, baseURL, apiKey, model)
}

func NewOpenAIResponsesProvider(id, baseURL, apiKey, model string) *OpenAIResponsesProvider {
	return core.NewOpenAIResponsesProvider(id, baseURL, apiKey, model)
}

func NewPerplexitySearchProvider(options PerplexitySearchProviderOptions) *PerplexitySearchProvider {
	return core.NewPerplexitySearchProvider(options)
}

func NewSQLiteSessionStore(path string, journalMode SQLiteJournalMode) (*SQLiteSessionStore, error) {
	return core.NewSQLiteSessionStore(path, journalMode)
}

func NewSQLiteSessionStoreWithOptions(options SQLiteSessionStoreOptions) (*SQLiteSessionStore, error) {
	return core.NewSQLiteSessionStoreWithOptions(options)
}

func NewSQLiteStorageBackend(path string, journalMode SQLiteJournalMode) (*SQLiteStorageBackend, error) {
	return core.NewSQLiteStorageBackend(path, journalMode)
}

func NewServer(e *Engine) *Server {
	return core.NewServer(e)
}

func NewSessionProjectionRegistry() *SessionProjectionRegistry {
	return core.NewSessionProjectionRegistry()
}

func NewStdioLSPProvider(id string, config LSPStdioConfig) (LSPProvider, error) {
	return core.NewStdioLSPProvider(id, config)
}

func NewStorageHub() *StorageHub {
	return core.NewStorageHub()
}

func NewWorkspaceFileSearch(root string, config FileReferenceConfig) (*WorkspaceFileSearch, error) {
	return core.NewWorkspaceFileSearch(root, config)
}

func NoSubagentStartCapabilities() SubagentCapabilities {
	return core.NoSubagentStartCapabilities()
}

func NormalizeSessionTitle(input string, maxBytes int) string {
	return core.NormalizeSessionTitle(input, maxBytes)
}

func ParseActiveFileReferenceToken(line string, cursorByte int) (ActiveFileReferenceToken, bool) {
	return core.ParseActiveFileReferenceToken(line, cursorByte)
}

func ParseCredentialKey(value string) (CredentialKey, error) {
	return core.ParseCredentialKey(value)
}

func ParseCredentialRef(value string) (CredentialRef, error) {
	return core.ParseCredentialRef(value)
}

func ParseHookOutput(exitCode *int, stdout, stderr string, expectedEvent ...string) HookOutput {
	return core.ParseHookOutput(exitCode, stdout, stderr, expectedEvent...)
}

func ParseSessionReferenceText(text string) (ParsedSessionReferenceText, error) {
	return core.ParseSessionReferenceText(text)
}

func PythonLogTruncationMarker(maxBytes int) string {
	return core.PythonLogTruncationMarker(maxBytes)
}

func RenderIndexInjections(html string, rows []IndexInjection) (string, error) {
	return core.RenderIndexInjections(html, rows)
}

func RunLandlockLauncher(args []string, stdout, stderr io.Writer) int {
	return core.RunLandlockLauncher(args, stdout, stderr)
}

func RunWithListener(ctx context.Context, e *Engine, listener net.Listener) error {
	return core.RunWithListener(ctx, e, listener)
}

func SearchWorkspaceFileReferences(ctx context.Context, root, rawQuery string, config FileReferenceConfig) ([]FileReferenceCandidate, error) {
	return core.SearchWorkspaceFileReferences(ctx, root, rawQuery, config)
}

func SessionProjectKey(cwd string) string {
	return core.SessionProjectKey(cwd)
}

func SummarizeHookStderr(stderr string, maxChars int) string {
	return core.SummarizeHookStderr(stderr, maxChars)
}

func TLSConfig(certFile, keyFile string) (*tls.Config, error) {
	return core.TLSConfig(certFile, keyFile)
}

func ValidStorageUnitName(name string) bool {
	return core.ValidStorageUnitName(name)
}

func ValidateDomainSpec(spec DomainSpec) error {
	return core.ValidateDomainSpec(spec)
}

func ValidatePythonChildFrame(raw any) (PythonChildFrame, bool) {
	return core.ValidatePythonChildFrame(raw)
}

func WithAPIKey(v string) Option {
	return core.WithAPIKey(v)
}

func WithAgentTeams(v AgentTeamConfig) Option {
	return core.WithAgentTeams(v)
}

func WithBaseURL(v string) Option {
	return core.WithBaseURL(v)
}

func WithBundledBadgeSkill(v bool) Option {
	return core.WithBundledBadgeSkill(v)
}

func WithClientHMRPollInterval(v time.Duration) Option {
	return core.WithClientHMRPollInterval(v)
}

func WithClientPlugins(v ...string) Option {
	return core.WithClientPlugins(v...)
}

func WithCompaction(v CompactionConfig) Option {
	return core.WithCompaction(v)
}

func WithConfig(c Config) Option {
	return core.WithConfig(c)
}

func WithDataDir(v string) Option {
	return core.WithDataDir(v)
}

func WithDynamicCordisVMTimeout(v time.Duration) Option {
	return core.WithDynamicCordisVMTimeout(v)
}

func WithE2B(v E2BConfig) Option {
	return core.WithE2B(v)
}

func WithFileReference(v FileReferenceConfig) Option {
	return core.WithFileReference(v)
}

func WithFrontendDir(v string) Option {
	return core.WithFrontendDir(v)
}

func WithHooks(v ...HookBridgeConfig) Option {
	return core.WithHooks(v...)
}

func WithLSPServers(v map[string]LSPStdioConfig) Option {
	return core.WithLSPServers(v)
}

func WithLSPTool(v LSPToolConfig) Option {
	return core.WithLSPTool(v)
}

func WithLaunchEnvironment(v *LaunchEnvironmentSnapshot) Option {
	return core.WithLaunchEnvironment(v)
}

func WithMCPServers(configs ...MCPConfig) Option {
	return core.WithMCPServers(configs...)
}

func WithModel(v string) Option {
	return core.WithModel(v)
}

func WithPersistence(v bool) Option {
	return core.WithPersistence(v)
}

func WithPluginDir(v string) Option {
	return core.WithPluginDir(v)
}

func WithPluginDirs(v ...string) Option {
	return core.WithPluginDirs(v...)
}

func WithProvider(v string) Option {
	return core.WithProvider(v)
}

func WithRepeatToolReminder(v RepeatToolReminderConfig) Option {
	return core.WithRepeatToolReminder(v)
}

func WithRetryPolicy(v RetryPolicy) Option {
	return core.WithRetryPolicy(v)
}

func WithRuntimeInvariants(v RuntimeInvariantConfig) Option {
	return core.WithRuntimeInvariants(v)
}

func WithSchedule(v bool) Option {
	return core.WithSchedule(v)
}

func WithSessionProjectionCache(config SessionProjectionCacheConfig) Option {
	return core.WithSessionProjectionCache(config)
}

func WithSessionReference(v SessionReferenceConfig) Option {
	return core.WithSessionReference(v)
}

func WithSessionStore(v SessionStore) Option {
	return core.WithSessionStore(v)
}

func WithSessionTelemetry(v *SessionTelemetryConfig) Option {
	return core.WithSessionTelemetry(v)
}

func WithSessionTitleLLM(v bool) Option {
	return core.WithSessionTitleLLM(v)
}

func WithSpill(v SpillConfig) Option {
	return core.WithSpill(v)
}

func WithStorageRuntime(v StorageRuntimeConfig) Option {
	return core.WithStorageRuntime(v)
}

func WithSubagentProviders(v ...SubagentProvider) Option {
	return core.WithSubagentProviders(v...)
}

func WithSubagentReportDelivery(v string) Option {
	return core.WithSubagentReportDelivery(v)
}

func WithSubagentTools(v ...SubagentToolConfig) Option {
	return core.WithSubagentTools(v...)
}

func WithTerminal(v TerminalConfig) Option {
	return core.WithTerminal(v)
}

func WithTerminalTool(v TerminalToolConfig) Option {
	return core.WithTerminalTool(v)
}

func WithTimeContext(v TimeContextConfig) Option {
	return core.WithTimeContext(v)
}

func WithTmuxContext(v TmuxContextConfig) Option {
	return core.WithTmuxContext(v)
}

func WithToolResultPruner(v ToolResultPruneConfig) Option {
	return core.WithToolResultPruner(v)
}

func WithWebFetchProvider(v string) Option {
	return core.WithWebFetchProvider(v)
}

func WithWebSearchProvider(v string) Option {
	return core.WithWebSearchProvider(v)
}

func WithWorkspace(v string) Option {
	return core.WithWorkspace(v)
}
