package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const coreImport = "github.com/xxnuo/deepseek-harness-go/internal/harness"

var excluded = map[string]bool{
	"AssetPaths":       true,
	"ConfigureRuntime": true,
	"Version":          true,
}

type declaration struct {
	kind       string
	name       string
	typeParams *ast.FieldList
	function   *ast.FuncDecl
	imports    map[string]string
}

func main() {
	input := flag.String("input", "internal/harness", "implementation package directory")
	output := flag.String("output", "facade_gen.go", "generated facade file")
	check := flag.Bool("check", false, "verify without writing")
	flag.Parse()

	declarations, imports, err := scan(*input)
	if err != nil {
		fatal(err)
	}
	data, err := render(declarations, imports)
	if err != nil {
		fatal(err)
	}
	if *check {
		current, err := os.ReadFile(*output)
		if err != nil || !bytes.Equal(current, data) {
			fatal(fmt.Errorf("%s is stale; run go run ./scripts/gen_public_facade", *output))
		}
		return
	}
	if err := os.WriteFile(*output, data, 0o644); err != nil {
		fatal(err)
	}
}

func scan(directory string) ([]declaration, map[string]string, error) {
	entries, err := os.ReadDir(directory)
	if err != nil {
		return nil, nil, err
	}
	fset := token.NewFileSet()
	byName := map[string]declaration{}
	usedImports := map[string]string{}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fset, filepath.Join(directory, entry.Name()), nil, 0)
		if err != nil {
			return nil, nil, err
		}
		fileImports := importAliases(file)
		for _, raw := range file.Decls {
			switch node := raw.(type) {
			case *ast.FuncDecl:
				if node.Recv != nil || !node.Name.IsExported() || excluded[node.Name.Name] {
					continue
				}
				if _, exists := byName[node.Name.Name]; exists {
					continue
				}
				imports := referencedImports(node.Type, fileImports)
				for alias, path := range imports {
					usedImports[alias] = path
				}
				byName[node.Name.Name] = declaration{kind: "func", name: node.Name.Name, function: node, imports: imports}
			case *ast.GenDecl:
				for _, spec := range node.Specs {
					switch spec := spec.(type) {
					case *ast.TypeSpec:
						if spec.Name.IsExported() && !excluded[spec.Name.Name] {
							byName[spec.Name.Name] = declaration{kind: "type", name: spec.Name.Name, typeParams: spec.TypeParams}
						}
					case *ast.ValueSpec:
						for _, name := range spec.Names {
							if name.IsExported() && !excluded[name.Name] {
								byName[name.Name] = declaration{kind: strings.ToLower(node.Tok.String()), name: name.Name}
							}
						}
					}
				}
			}
		}
	}
	declarations := make([]declaration, 0, len(byName))
	for _, item := range byName {
		declarations = append(declarations, item)
	}
	sort.Slice(declarations, func(i, j int) bool {
		order := map[string]int{"const": 0, "var": 1, "type": 2, "func": 3}
		if order[declarations[i].kind] != order[declarations[j].kind] {
			return order[declarations[i].kind] < order[declarations[j].kind]
		}
		return declarations[i].name < declarations[j].name
	})
	return declarations, usedImports, nil
}

func importAliases(file *ast.File) map[string]string {
	aliases := map[string]string{}
	for _, item := range file.Imports {
		path, err := strconv.Unquote(item.Path.Value)
		if err != nil {
			continue
		}
		alias := filepath.Base(path)
		if item.Name != nil {
			alias = item.Name.Name
		}
		if alias != "_" && alias != "." {
			aliases[alias] = path
		}
	}
	return aliases
}

func referencedImports(node ast.Node, available map[string]string) map[string]string {
	used := map[string]string{}
	ast.Inspect(node, func(node ast.Node) bool {
		selector, ok := node.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		identifier, ok := selector.X.(*ast.Ident)
		if !ok {
			return true
		}
		if path := available[identifier.Name]; path != "" {
			used[identifier.Name] = path
		}
		return true
	})
	return used
}

func render(declarations []declaration, imports map[string]string) ([]byte, error) {
	var output strings.Builder
	output.WriteString("// Code generated by scripts/gen_public_facade; DO NOT EDIT.\n\n")
	output.WriteString("package harness\n\n")
	output.WriteString("import (\n\tcore \"")
	output.WriteString(coreImport)
	output.WriteString("\"\n")
	aliases := make([]string, 0, len(imports))
	for alias := range imports {
		aliases = append(aliases, alias)
	}
	sort.Strings(aliases)
	for _, alias := range aliases {
		fmt.Fprintf(&output, "\t%s %q\n", alias, imports[alias])
	}
	output.WriteString(")\n")

	for _, item := range declarations {
		output.WriteString("\n")
		switch item.kind {
		case "const":
			fmt.Fprintf(&output, "const %s = core.%s\n", item.name, item.name)
		case "var":
			fmt.Fprintf(&output, "var %s = core.%s\n", item.name, item.name)
		case "type":
			fmt.Fprintf(&output, "type %s%s = core.%s%s\n", item.name, fieldList(item.typeParams), item.name, typeArguments(item.typeParams))
		case "func":
			if err := writeFunction(&output, item.function); err != nil {
				return nil, err
			}
		}
	}
	return format.Source([]byte(output.String()))
}

func writeFunction(output *strings.Builder, function *ast.FuncDecl) error {
	parameters := cloneFieldList(function.Type.Params)
	arguments := make([]string, 0)
	index := 0
	for fieldIndex, field := range parameters.List {
		if len(field.Names) == 0 {
			name := fmt.Sprintf("arg%d", index)
			index++
			field.Names = []*ast.Ident{ast.NewIdent(name)}
		}
		for _, name := range field.Names {
			if name.Name == "_" {
				name.Name = fmt.Sprintf("arg%d", index)
				index++
			}
			argument := name.Name
			if fieldIndex == len(parameters.List)-1 {
				if _, ok := field.Type.(*ast.Ellipsis); ok {
					argument += "..."
				}
			}
			arguments = append(arguments, argument)
		}
	}
	signature := &ast.FuncType{TypeParams: function.Type.TypeParams, Params: parameters, Results: function.Type.Results}
	var rendered bytes.Buffer
	if err := format.Node(&rendered, token.NewFileSet(), signature); err != nil {
		return err
	}
	typeArgs := typeArguments(function.Type.TypeParams)
	fmt.Fprintf(output, "func %s%s {\n", function.Name.Name, strings.TrimPrefix(rendered.String(), "func"))
	call := fmt.Sprintf("core.%s%s(%s)", function.Name.Name, typeArgs, strings.Join(arguments, ", "))
	if function.Type.Results == nil || len(function.Type.Results.List) == 0 {
		fmt.Fprintf(output, "\t%s\n", call)
	} else {
		fmt.Fprintf(output, "\treturn %s\n", call)
	}
	output.WriteString("}\n")
	return nil
}

func cloneFieldList(fields *ast.FieldList) *ast.FieldList {
	if fields == nil {
		return nil
	}
	clone := &ast.FieldList{Opening: fields.Opening, Closing: fields.Closing, List: make([]*ast.Field, len(fields.List))}
	for index, field := range fields.List {
		item := *field
		item.Names = make([]*ast.Ident, len(field.Names))
		for nameIndex, name := range field.Names {
			copy := *name
			item.Names[nameIndex] = &copy
		}
		clone.List[index] = &item
	}
	return clone
}

func fieldList(fields *ast.FieldList) string {
	if fields == nil || len(fields.List) == 0 {
		return ""
	}
	var output bytes.Buffer
	signature := &ast.FuncType{TypeParams: fields, Params: &ast.FieldList{}}
	if err := format.Node(&output, token.NewFileSet(), signature); err != nil {
		fatal(err)
	}
	value := strings.TrimPrefix(output.String(), "func")
	return strings.TrimSuffix(value, "()")
}

func typeArguments(fields *ast.FieldList) string {
	if fields == nil || len(fields.List) == 0 {
		return ""
	}
	var names []string
	for _, field := range fields.List {
		for _, name := range field.Names {
			names = append(names, name.Name)
		}
	}
	return "[" + strings.Join(names, ", ") + "]"
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
